library("jsonlite")
library(dplyr)
cook<- fromJSON("train.json")
View(cook)
library(dplyr)
cuisine_freq<- cook %>% group_by(cuisine) %>% summarize(count=n())
library(ggplot2)
plot<- ggplot(cuisine_freq, aes(cuisine, count)) + geom_point() + theme_bw()
library(tm)
ingredients<- Corpus(VectorSource(cook$ingredients))
tdm<- TermDocumentMatrix(ingredients)
sparse<- removeSparseTerms(tdm, 0.99)
final_ingredients<- as.data.frame(as.matrix(sparse))
final_ingredients<- t(final_ingredients)
cuisine<- as.data.frame(cuisine=cook$cuisine)
final_cook<- cbind(final_ingredients, cuisine)
write.csv(final_cook, file="cooking.csv")
library(rattle)
rattle()
